app/user/views.py
"""User views."""
from flask import Blueprint, render_template, request, jsonify
from flask_login import login_required, login_user, logout_user, current_user
from app.extensions import login_manager, csrf_protect, db
from app.plan.models import Plan
from app.task.models import Task

blueprint = Blueprint("user", __name__, url_prefix="/users", static_folder="../static")

@blueprint.route("/")
@login_required
def members():
    return render_template("users/member_page.html")

@blueprint.route("/load_content/", methods=["GET"])
@csrf_protect.exempt
@login_required
def load_content():
    # return every plan and task belonging to current_user
    plans = Plan.query.filter_by(user_id=current_user.id).all()
    tasks = Task.query.filter_by(user_id=current_user.id).all()
    return jsonify({
        "plans": [p.makedict() for p in plans],
        "tasks": [t.makedict() for t in tasks],
    })

@blueprint.route("/load_plans/", methods=["POST"])
@csrf_protect.exempt
@login_required
def load_plans():
    plans = Plan.query.filter_by(user_id=current_user.id).all()
    return jsonify({
        "plans": [
            {"name": plan.name,
            "description": plan.description,
            "planId": plan.id
            } for plan in plans
        ]
    })

@blueprint.route("/get_plan_details/", methods=["POST"])
@csrf_protect.exempt
@login_required
def get_plan_details():
    data = request.get_json()
    plan_id = data["plan_id"]
    tasks = Task.query.filter_by(plan=plan_id)
    return jsonify({
        "tasks": [
            {
            "name": task.name,
            "description": task.description,
            "taskId": task.id
            } for task in tasks
        ],
        "planId": plan_id,
    })


@blueprint.route("/add_plan/", methods=["POST"])
@csrf_protect.exempt
@login_required
def add_plan():
    data = request.get_json()
    user_id = current_user.id
    new_plan = Plan(
        user_id=user_id,
        name=data["name"],
        description=data["description"],
    )
    try:
        new_plan.save(commit=True)
    except IntegrityError as exc:
        return jsonify({
            "success": False,
            "result": "Plan name taken",
            "exc": str(exc)
            })
    return jsonify({
        "success": True,
        "result": "Plan saved to database",
        "name": data["name"],
        "description": data["description"],
        "planId": new_plan.id
    })


@blueprint.route("/add_task/", methods=["POST"])
@csrf_protect.exempt
@login_required
def add_task():
    data = request.get_json()
    user_id = current_user.id
    new_task = Task(
        user_id=user_id,
        name=data["name"],
        description=data["description"],
        plan=data["plan_id"],
    )
    try:
        new_task.save(commit=True)
    except IntegrityError as exc:
        return jsonify({
            "success": False,
            "result": "Name Taken",
            "exc": str(exc),
        })
    return jsonify({
        "success": True,
        "result": "Task saved to database",
        "name": data["name"],
        "description": data["description"],
        "taskId": new_task.id,
        "planId": data["plan_id"],
    })


@blueprint.route("/delete_plan/", methods=["POST"])
@csrf_protect.exempt
@login_required
def delete_plan():
    data = request.get_json()
    plan = Plan.query.filter_by(id=data["planId"])[0]
    result = plan.delete(commit=True)
    return jsonify({
        "result": True,
        "planId": data["planId"]
    })

@blueprint.route("/delete_task/", methods=["POST"])
@csrf_protect.exempt
@login_required
def delete_task():
    data = request.get_json()
    task = Task.query.filter_by(id=data["taskId"])[0]
    result = task.delete(commit=True)
    return jsonify({
        "result": True,
        "taskId": data["taskId"]
    })

app/templates/footer.html
<footer>
    <small>
  
      <ul class="footer-nav">
  
        <li><a href="{{ url_for('public.about') }}">About</a></li>
  
        <li><a href="mailto:torbjorngul@gmail.com">Contact</a></li>
      </ul>
    </small>
  </footer>
  

app/templates/layout.html

<!DOCTYPE html>
<html class="no-js" lang="en">
  <head>
    <meta charset="utf-8" />
    <link rel="manifest" href="{{ url_for('static', filename='manifest.json') }}">
    <link rel="shortcut icon" href="{{static_url_for('static', filename='favicon.ico') }}">
    <title>
      {% block page_title %} 
        pwa_flask_app
      {% endblock %}
    </title>
    <meta
      name="description"
      content="{% block meta_description %}{% endblock %}"
    />
    <meta name="author" content="{% block meta_author %}{% endblock %}" />

    <!-- Mobile viewport optimized: h5bp.com/viewport -->
    <meta name="viewport" content="width=device-width" />

    <link
      rel="stylesheet"
      type="text/css"
      href="{{ static_url_for('static', filename='main.css') }}"
    />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    {% block css %}{% endblock %}
  </head>
  <body class="{% block body_class %}{% endblock %}">
    {% block body %} {% with form=form %} {% include "nav.html" %} {% endwith %}

    <header>{% block header %}{% endblock %}</header>

    <main role="main">
      <p id="pwa-message" class="message"></p>
      {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
      <div class="row">
        <div class="col-md-12">
          {% for category, message in messages %}
          <div class="alert alert-{{ category }}">
            <a class="close" title="Close" href="#" data-dismiss="alert">&times;</a>
            {{ message }}
          </div>
          {% endfor %}
        </div>
      </div>
      {% endif %} {% endwith %} {% block content %}{% endblock %}
    </main>
    {% include "footer.html" %}
    <script src="{{ url_for('static', filename='jquery.min.js') }}"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/js/all.min.js"></script>
    <script src="{{ url_for('static', filename='idb-promised.js') }}"></script>
    <script src="{{ url_for('static', filename='app.js') }}"></script>
    {% block js %}{% endblock %}
    {% endblock %}
  </body>
</html>


app/templates/nav.html

<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <a class="navbar-brand" href="{{ url_for('public.home') }}">
       pwa_flask_app
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
      aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{{ url_for('public.home') }}">Home
            <span class="sr-only">(current)</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('public.about') }}">About</a>
        </li>
      </ul>
      {% if current_user and current_user.is_authenticated %}
      <ul class="navbar-nav my-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{{ url_for('user.members') }}">Logged in as {{ current_user.username }}</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('public.logout') }}">
            <i class="fa fa-sign-out-alt"></i>
          </a>
        </li>
      </ul>
      {% elif form %}
      <form class="form-inline" id="loginForm" method="POST" role="login">
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
        <div class="input-group mb-2 mr-sm-2">
          {{ form.username(placeholder="Username", class_="form-control mr-sm-1 my-auto") }} {{ form.password(placeholder="Password",
          class_="form-control mr-sm-1 my-auto") }}
          <button class="btn btn-light btn-primary m-auto" type="submit">Login</button>
        </div>
      </form>
      <ul class="navbar-nav my-auto">
        <li class="nav-item">
          <a class="nav-link navbar-text" href="{{ url_for('public.register') }}">Create account</a>
        </li>
      </ul>
      {% endif %}
    </div><!-- /.navbar-collapse -->
  </nav>
  

app/templates/offline.html
<!DOCTYPE html>
<html lang="en">
    Offline mode
</html> 